version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback 
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - setup_remote_docker
      - run: npm test
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: "Build docker image and push o docker hub"
          command: |
            cp Dockerfile.production Dockerfile
            docker build -t krittanun/example-nodejs-circle:lastest .
            docker build -t krittanun/example-nodejs-circle:${CIRCLE_SHA1} .
            docker push krittanun/example-nodejs-circle:lastest
            docker push krittanun/example-nodejs-circle:${CIRCLE_SHA1}
      - run: echo Done
      - run: echo Hey
